ALTER TABLE [NDTUAT].[CustomReportTemplateDetails]
    ADD CONSTRAINT [PK_CustomReportTemplateDetails] PRIMARY KEY CLUSTERED ([CustomReportTemplateDetailsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

