ALTER TABLE [NDTUAT].[LiquidPenetrantExaminationTest]
    ADD CONSTRAINT [PK_LiquidPenetrantExaminationTest] PRIMARY KEY CLUSTERED ([ReportId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

