ALTER TABLE [NDTUAT].[LookUpMaster]
    ADD CONSTRAINT [PK_LookUpSU] PRIMARY KEY CLUSTERED ([LookupCode] ASC, [ParamKey] ASC, [SubTestId] ASC, [ClientID] ASC, [DeletedStatus] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

