ALTER TABLE [NDTUAT].[MagneticParticleExaminationTestResults]
    ADD CONSTRAINT [PK_MagneticParticleExaminationTestResults] PRIMARY KEY CLUSTERED ([TestId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

