ALTER TABLE [NDTUAT].[NdtExceptionLog]
    ADD CONSTRAINT [PK_NdtExceptionLog] PRIMARY KEY CLUSTERED ([autoid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

