ALTER TABLE [NDTUAT].[RadiographicWeldTestResult]
    ADD CONSTRAINT [PK_RadiographicWeldTestResult] PRIMARY KEY CLUSTERED ([TestId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

