ALTER TABLE [NDTUAT].[TechniqueSheetDetails]
    ADD CONSTRAINT [PK_TechniqueSheetsDetail] PRIMARY KEY CLUSTERED ([TechniqueId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

