ALTER TABLE [NDTUAT].[Users]
    ADD CONSTRAINT [users_emailid_UK] UNIQUE NONCLUSTERED ([EmailId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

