CREATE TABLE [NDTUAT].[MagneticParticleExaminationTest] (
    [ReportId]             INT            IDENTITY (1, 1) NOT NULL,
    [FabricatorName]       NVARCHAR (200) NOT NULL,
    [SubTestId]            INT            NOT NULL,
    [Location]             NVARCHAR (200) NULL,
    [ReportNo]             NVARCHAR (50)  NULL,
    [ContractNo]           NVARCHAR (50)  NOT NULL,
    [ContactPerson]        NVARCHAR (50)  NULL,
    [DateofTesting]        DATETIME       NOT NULL,
    [JobDescription]       NVARCHAR (200) NULL,
    [Material]             NVARCHAR (50)  NULL,
    [Dimension]            NVARCHAR (50)  NULL,
    [SurfaceCondition]     NVARCHAR (50)  NULL,
    [ReferenceCode]        INT            NULL,
    [AcceptanceCriteria]   NVARCHAR (50)  NULL,
    [TechSheetNo]          NVARCHAR (50)  NULL,
    [ExtentofCoverage]     NVARCHAR (50)  NULL,
    [SurfaceTemperature]   NVARCHAR (50)  NULL,
    [ConsumablesType]      INT            NULL,
    [TechniqueId]          INT            NULL,
    [Direction]            NVARCHAR (50)  NULL,
    [MagnetizationCurrent] NVARCHAR (50)  NULL,
    [DetectionMedia]       NVARCHAR (50)  NULL,
    [Concentration]        NVARCHAR (50)  NULL,
    [Illuminance]          NVARCHAR (50)  NULL,
    [ContrastPaint]        NVARCHAR (50)  NULL,
    [Demagnetizing]        NVARCHAR (50)  NULL,
    [Equipment]            NVARCHAR (50)  NULL,
    [CalibrationStatus]    NVARCHAR (50)  NULL,
    [Amperage]             NVARCHAR (50)  NULL,
    [Spacing]              NVARCHAR (50)  NULL,
    [BlackLightIntensity]  NVARCHAR (50)  NULL,
    [FieldIndicator]       NVARCHAR (50)  NULL,
    [FinalCleaning]        NVARCHAR (50)  NULL,
    [AppId]                INT            NULL,
    [ClientId]             INT            NULL,
    [CreatedBy]            INT            NULL,
    [CreatedDate]          DATETIME       NULL,
    [UpdatedBy]            INT            NULL,
    [UpdatedDate]          DATETIME       NULL,
    [DeletedStatus]        SMALLINT       NULL
);

