ALTER TABLE [MiEFW].[mstFunctionalityinfo]
    ADD CONSTRAINT [PK_mstFunctionalityinfo] PRIMARY KEY CLUSTERED ([functionalityid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

