ALTER TABLE [MiEFW].[mstroleinfo]
    ADD CONSTRAINT [PK_mstroleinfo] PRIMARY KEY CLUSTERED ([roleid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

