ALTER TABLE [MiEFW].[MiDBTool_ReportMaster]
    ADD CONSTRAINT [PK_MiDBTool_ReportMaster] PRIMARY KEY CLUSTERED ([StoreID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

