ALTER TABLE [MiEFW].[MstDevComponents_Attributes]
    ADD CONSTRAINT [PK_MstDevComponents_Attributes] PRIMARY KEY CLUSTERED ([AutoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

