ALTER TABLE [MiEFW].[MiDBTool_ParameterMaster]
    ADD CONSTRAINT [PK_MiDBTool_ParameterMaster] PRIMARY KEY CLUSTERED ([autoid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

