ALTER TABLE [MiEFW].[SPManager_ProcMaster]
    ADD CONSTRAINT [PK_SPManager_ProcMaster] PRIMARY KEY CLUSTERED ([StoreID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

