ALTER TABLE [MiEFW].[mstLayout]
    ADD CONSTRAINT [PK_Table_1_1] PRIMARY KEY CLUSTERED ([AutoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

