CREATE PROCEDURE [NDTUAT].[prc_InsertRadiographicWeld]
(
   @ReportId int = 0,
   @Client nvarchar(400),
   @Location nvarchar(400),
   @ContactPerson nvarchar(400),
   @TestReportNumber nvarchar(100),
   @JobDescription nvarchar(1000),
   @TestDate varchar(50),
   @ContractNo nvarchar(100),
   @RefDocumentId int,
   @RadiationSourceId int,
   @FilmMakeAndType varchar(100),
   @TypeofIQI varchar(50),
   @IQIBatchNo varchar(50),
   @TechniqueId int,
   @ShimThickness varchar(50),
   @DensitometerNo varchar(50),
   @CalibrationDate varchar(50),
   @GeometricalUnsharpness varchar(50),
   @MaterialSpecification varchar(50),
   @SurfaceCondition varchar(50),
   @SurfaceTemperature varchar(50),
   @ExtentofExamination varchar(50),
   @Dimension varchar(50),
   @WeldThickness varchar(50),
   @WeldPreparation varchar(50),
   @StageofExamination varchar(50),
   @ContactNumber varchar(30),
   @SFD varchar(50),
   @WeldingMethod varchar(50),
   @ExposureTime nvarchar(100),
   @SubTestId int,
   @AppID int = null,
   @ClientID int = null,
   @CreatedBy int = null,
   @CreatedDate varchar(50) = null,
   @UpdatedBy int = null,
   @UpdatedDate varchar(50) = null,
   @DeletedStatus smallint  = 0
)
AS
BEGIN -- BEGIN PROC
--<VALIDATE INPUT PARAMS> IF INVALID RETURN <CUSTOM_ERROR_CODE>
--<CHECK EXISTANCE IN DB>
   BEGIN TRY
         INSERT INTO NDTUAT.RadiographicWeld
         (
			Client,
			Location,
			ContactPerson,
			TestReportNumber,
			JobDescription,
			TestDate,
			ContractNo,
			RefDocumentId,
			RadiationSourceId,
			FilmMakeAndType,
			TypeofIQI,
			IQIBatchNo,
			TechniqueId,
			ShimThickness,
			DensitometerNo,
			CalibrationDate,
			GeometricalUnsharpness,
			MaterialSpecification,
			SurfaceCondition,
			SurfaceTemperature,
			ExtentofExamination,
			Dimension,
			WeldThickness,
			WeldPreparation,
			StageofExamination,
			ContactNumber,
			SFD,
			WeldingMethod,
			ExposureTime,
			SubTestId,
			AppID,
			ClientID,
			CreatedBy,
			CreatedDate,
			UpdatedBy,
			UpdatedDate,
			DeletedStatus
		)
         SELECT
			@Client,
			@Location,
			@ContactPerson,
			@TestReportNumber,
			@JobDescription,
			Case when Isnull(@TestDate,'') = '' Then Null Else Convert(Datetime,@TestDate,103) End as TestDate,
			@ContractNo,
			@RefDocumentId,
			@RadiationSourceId,
			@FilmMakeAndType,
			@TypeofIQI,
			@IQIBatchNo,
			@TechniqueId,
			@ShimThickness,
			@DensitometerNo,
			Case when Isnull(@CalibrationDate,'') = '' Then Null Else Convert(Datetime,@CalibrationDate,103) End as CalibrationDate,
			@GeometricalUnsharpness,
			@MaterialSpecification,
			@SurfaceCondition,
			@SurfaceTemperature,
			@ExtentofExamination,
			@Dimension,
			@WeldThickness,
			@WeldPreparation,
			@StageofExamination,
			@ContactNumber,
			@SFD,
			@WeldingMethod,
			@ExposureTime,
			@SubTestId,
			@AppID,
			@ClientID,
			@CreatedBy,
			GETDATE(),
			null,
			null,
			0
         SELECT SCOPE_IDENTITY();
   END TRY
   BEGIN CATCH
      --ROLLBACK TRAN
      --LOG ERROR IN DB
      EXEC [NDTUAT].[usp_GetErrorInfo]
      RETURN
   END CATCH
END -- END PROC
