
CREATE PROCEDURE [NDTUAT].[prc_GetObservations]
@ClientId int
AS
BEGIN -- BEGIN PROC
	--<VALIDATE INPUT PARAMS> IF INVALID RETURN <CUSTOM_ERROR_CODE>
	--<CHECK EXISTANCE IN DB>
	BEGIN TRY
		SELECT ObservationsId, ObservationsShortName 
		FROM NDTUAT.Observations
		WHERE DeletedStatus=0 
		AND ClientId=@ClientId
	END TRY
	BEGIN CATCH
		--LOG ERROR IN DB
		EXEC [NDTUAT].[usp_GetErrorInfo]  
		RETURN		
	END CATCH
END -- END PROC

