CREATE PROCEDURE [NDTUAT].[usp_GetAppExceptions]
AS
BEGIN -- BEGIN PROC
   --<VALIDATE INPUT PARAMS> IF INVALID RETURN <CUSTOM_ERROR_CODE>
   --<CHECK EXISTANCE IN DB>
   BEGIN TRY
      BEGIN TRAN
       --<YOUR CODE GOES HERE>
	  SELECT TOP 100 * FROM NDTUAT.NdtExceptionLog ORDER BY 1 DESC
      COMMIT TRAN
   END TRY
   BEGIN CATCH
      ROLLBACK TRAN
      --LOG ERROR IN DB
      EXEC [NDTUAT].[usp_GetErrorInfo]
      RETURN
   END CATCH
END -- END PROC


