CREATE PROCEDURE [NDTUAT].[usp_CreateProcTemplate]
(
    @Param1 int,
    @Param2 nvarchar(max)
)
AS
BEGIN -- BEGIN PROC
   --<VALIDATE INPUT PARAMS> IF INVALID RETURN <CUSTOM_ERROR_CODE>
   --<CHECK EXISTANCE IN DB>
   BEGIN TRY
      BEGIN TRAN
       --<YOUR CODE GOES HERE>
      COMMIT TRAN
   END TRY
   BEGIN CATCH
      ROLLBACK TRAN
      --LOG ERROR IN DB
      EXEC [NDTUAT].[usp_GetErrorInfo]
      RETURN
   END CATCH
END -- END PROC

